#include <cstdint>
#include <ctime>
#include <memory>
#include <vector>

#include "core/GameEngine.hpp"
#include "core/PerlinNoise.hpp"
#include "Chunk.hpp"

namespace {
    constexpr int WORLD_SIZE = 512; // blocks along X and Z, covering [0, WORLD_SIZE)
    constexpr int CHUNKS_PER_AXIS = WORLD_SIZE / CHUNK_SIZE;
}

int main()
{
    GameEngine engine(1280, 720, "Mine-Clone");

    PerlinNoise terrain_noise(static_cast<uint32_t>(time(nullptr)));

    // Two passes: every chunk's blocks first, then every chunk's mesh — mesh
    // building culls a chunk's boundary faces against its neighbors' blocks,
    // so those neighbors need to already be generated by the time it runs.
    // (Lighting is still computed per chunk in isolation, so a faint AO/light
    // seam can still show at chunk borders even though the wall itself is
    // gone — that's still-future World work, not this pass.)
    std::vector<std::unique_ptr<Chunk>> chunks;
    chunks.reserve(CHUNKS_PER_AXIS * CHUNKS_PER_AXIS);
    for (int cx = 0; cx < CHUNKS_PER_AXIS; ++cx) {
        for (int cz = 0; cz < CHUNKS_PER_AXIS; ++cz) {
            Vector3 position = {
                cx * static_cast<float>(CHUNK_SIZE),
                0.0f,
                cz * static_cast<float>(CHUNK_SIZE),
            };
            auto chunk = std::make_unique<Chunk>(position);
            chunk->generate_terrain(terrain_noise);
            chunk->compute_lighting();
            chunks.push_back(std::move(chunk));
        }
    }

    auto chunk_at = [&](int cx, int cz) -> Chunk* {
        if (cx < 0 || cx >= CHUNKS_PER_AXIS || cz < 0 || cz >= CHUNKS_PER_AXIS) return nullptr;
        return chunks[cx * CHUNKS_PER_AXIS + cz].get();
    };

    for (int cx = 0; cx < CHUNKS_PER_AXIS; ++cx) {
        for (int cz = 0; cz < CHUNKS_PER_AXIS; ++cz) {
            chunk_at(cx, cz)->build_mesh(chunk_at(cx - 1, cz), chunk_at(cx + 1, cz),
                                          chunk_at(cx, cz - 1), chunk_at(cx, cz + 1));
        }
    }

    for (auto& chunk : chunks) {
        engine.add_object(std::move(chunk));
    }

    engine.run();
    return 0;
}
