#include "World.hpp"
#include "core/PerlinNoise.hpp"

#include "raymath.h"

#include <cmath>
#include <limits>

namespace {
    // Rounds toward negative infinity, unlike C++'s truncating `/`, so a
    // world-space coordinate left of/above chunk 0 (negative x or z) still
    // maps to the chunk that actually contains it instead of off by one.
    int floor_div(int a, int b) {
        int quotient = a / b;
        int remainder = a % b;
        return (remainder != 0 && remainder < 0) ? quotient - 1 : quotient;
    }
}

World::World(int size_in_blocks, uint32_t seed)
    : chunks_per_axis(size_in_blocks / CHUNK_SIZE)
{
    chunks.reserve(static_cast<size_t>(chunks_per_axis) * chunks_per_axis);

    PerlinNoise terrain_noise(seed);

    // Two passes: every chunk's blocks first, then every chunk's mesh — mesh
    // building samples a chunk's boundary faces (and their AO/light) against
    // its neighbors' block and light data, so those neighbors need to
    // already be generated by the time it runs.
    for (int cx = 0; cx < chunks_per_axis; ++cx) {
        for (int cz = 0; cz < chunks_per_axis; ++cz) {
            Vector3 position = {
                cx * static_cast<float>(CHUNK_SIZE),
                0.0f,
                cz * static_cast<float>(CHUNK_SIZE),
            };
            auto chunk = std::make_unique<Chunk>(position);
            chunk->generate_terrain(terrain_noise);
            chunk->compute_lighting();
            chunks.push_back(std::move(chunk));
        }
    }

    for (int cx = 0; cx < chunks_per_axis; ++cx) {
        for (int cz = 0; cz < chunks_per_axis; ++cz) {
            rebuild_mesh(cx, cz);
        }
    }
}

Chunk* World::chunk_at(int chunk_x, int chunk_z)
{
    if (chunk_x < 0 || chunk_x >= chunks_per_axis || chunk_z < 0 || chunk_z >= chunks_per_axis) {
        return nullptr;
    }
    return chunks[static_cast<size_t>(chunk_x) * chunks_per_axis + chunk_z].get();
}

const Chunk* World::chunk_at(int chunk_x, int chunk_z) const
{
    if (chunk_x < 0 || chunk_x >= chunks_per_axis || chunk_z < 0 || chunk_z >= chunks_per_axis) {
        return nullptr;
    }
    return chunks[static_cast<size_t>(chunk_x) * chunks_per_axis + chunk_z].get();
}

void World::rebuild_mesh(int chunk_x, int chunk_z)
{
    Chunk* chunk = chunk_at(chunk_x, chunk_z);
    if (chunk == nullptr) return;

    chunk->build_mesh(
        chunk_at(chunk_x - 1, chunk_z),     chunk_at(chunk_x + 1, chunk_z),
        chunk_at(chunk_x, chunk_z - 1),     chunk_at(chunk_x, chunk_z + 1),
        chunk_at(chunk_x - 1, chunk_z - 1), chunk_at(chunk_x + 1, chunk_z - 1),
        chunk_at(chunk_x - 1, chunk_z + 1), chunk_at(chunk_x + 1, chunk_z + 1));
}

void World::draw() const
{
    for (const auto& chunk : chunks) {
        chunk->draw();
    }
}

BlockType World::get_block(int x, int y, int z) const
{
    if (y < 0 || y >= CHUNK_SIZE) return BlockType::Air; // no vertical chunk stacking yet

    int chunk_x = floor_div(x, CHUNK_SIZE);
    int chunk_z = floor_div(z, CHUNK_SIZE);
    const Chunk* chunk = chunk_at(chunk_x, chunk_z);
    if (chunk == nullptr) return BlockType::Air;

    return chunk->get_block(x - chunk_x * CHUNK_SIZE, y, z - chunk_z * CHUNK_SIZE);
}

int World::get_light(int x, int y, int z) const
{
    if (y < 0 || y >= CHUNK_SIZE) return MAX_LIGHT; // no vertical chunk stacking yet

    int chunk_x = floor_div(x, CHUNK_SIZE);
    int chunk_z = floor_div(z, CHUNK_SIZE);
    const Chunk* chunk = chunk_at(chunk_x, chunk_z);
    if (chunk == nullptr) return MAX_LIGHT; // edge of the loaded world

    return chunk->get_light(x - chunk_x * CHUNK_SIZE, y, z - chunk_z * CHUNK_SIZE);
}

World::ChunkCoordinates World::chunk_coordinates(int x, int z) const
{
    return {floor_div(x, CHUNK_SIZE), floor_div(z, CHUNK_SIZE)};
}

std::optional<World::RaycastHit> World::raycast(Vector3 origin, Vector3 direction, float max_distance) const
{
    Vector3 dir = Vector3Normalize(direction);

    int x = static_cast<int>(std::floor(origin.x));
    int y = static_cast<int>(std::floor(origin.y));
    int z = static_cast<int>(std::floor(origin.z));

    int step_x = (dir.x > 0.0f) ? 1 : (dir.x < 0.0f ? -1 : 0);
    int step_y = (dir.y > 0.0f) ? 1 : (dir.y < 0.0f ? -1 : 0);
    int step_z = (dir.z > 0.0f) ? 1 : (dir.z < 0.0f ? -1 : 0);

    constexpr float INF = std::numeric_limits<float>::infinity();

    // Distance (in units of `direction`'s length, i.e. world units since
    // `dir` is normalized) along the ray to the next boundary crossing on
    // each axis, and how much that distance grows every time this axis
    // crosses one more voxel boundary.
    auto next_boundary_t = [](float origin_coord, int voxel, int step, float dir_component) {
        if (step == 0) return INF;
        float boundary = static_cast<float>(step > 0 ? voxel + 1 : voxel);
        return (boundary - origin_coord) / dir_component;
    };
    auto boundary_t_step = [](int step, float dir_component) {
        return (step == 0) ? INF : std::fabs(1.0f / dir_component);
    };

    float t_max_x = next_boundary_t(origin.x, x, step_x, dir.x);
    float t_max_y = next_boundary_t(origin.y, y, step_y, dir.y);
    float t_max_z = next_boundary_t(origin.z, z, step_z, dir.z);

    float t_delta_x = boundary_t_step(step_x, dir.x);
    float t_delta_y = boundary_t_step(step_y, dir.y);
    float t_delta_z = boundary_t_step(step_z, dir.z);

    // Outward normal of the face the ray most recently entered the current
    // voxel through; {0,0,0} for the starting voxel (there's no "entry
    // face" if the ray already starts inside a solid block).
    Vector3 normal = {0.0f, 0.0f, 0.0f};
    float traveled = 0.0f;

    while (traveled <= max_distance) {
        if (get_block_properties(get_block(x, y, z)).solid) {
            return RaycastHit{x, y, z, normal};
        }

        if (t_max_x < t_max_y && t_max_x < t_max_z) {
            x += step_x;
            traveled = t_max_x;
            t_max_x += t_delta_x;
            normal = {static_cast<float>(-step_x), 0.0f, 0.0f};
        } else if (t_max_y < t_max_z) {
            y += step_y;
            traveled = t_max_y;
            t_max_y += t_delta_y;
            normal = {0.0f, static_cast<float>(-step_y), 0.0f};
        } else {
            z += step_z;
            traveled = t_max_z;
            t_max_z += t_delta_z;
            normal = {0.0f, 0.0f, static_cast<float>(-step_z)};
        }
    }

    return std::nullopt;
}

void World::break_block(int x, int y, int z)
{
    if (!get_block_properties(get_block(x, y, z)).solid) return; // nothing there to break
    set_block_and_rebuild(x, y, z, BlockType::Air);
}

void World::place_block(int x, int y, int z, BlockType type)
{
    if (get_block_properties(get_block(x, y, z)).solid) return; // something's already there
    set_block_and_rebuild(x, y, z, type);
}

void World::set_block_and_rebuild(int x, int y, int z, BlockType type)
{
    if (y < 0 || y >= CHUNK_SIZE) return;

    int chunk_x = floor_div(x, CHUNK_SIZE);
    int chunk_z = floor_div(z, CHUNK_SIZE);
    Chunk* chunk = chunk_at(chunk_x, chunk_z);
    if (chunk == nullptr) return;

    int local_x = x - chunk_x * CHUNK_SIZE;
    int local_z = z - chunk_z * CHUNK_SIZE;
    chunk->set_block(local_x, y, local_z, type);
    chunk->compute_lighting();

    for (int dx = -1; dx <= 1; ++dx) {
        for (int dz = -1; dz <= 1; ++dz) {
            rebuild_mesh(chunk_x + dx, chunk_z + dz);
        }
    }
}
